### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Koperlite** [rsmith-nl/stltools#10]
The script need README.txt but there is only a file README.rst in the archive.

workaround : 
 cp README.rst README.txt
before starting
 sudo python setup.py install

**Comment by rsmith-nl** [comment]
This was fixed in https://github.com/rsmith-nl/stltools/commit/8e6ec4ccc6a83098278295b8a07e7c2178fdbfba. Please make sure you are up to date on the current `master` branch.

Running `python3 setup.py install` works fine for me.
