### ISSUE TITLE
STL and POV-ray use different coordinate systems, so the image does not look "correct"

### ISSUE THREAD

**Issue by pmjdebruijn** [rsmith-nl/stltools#11]
I'm under the impression that stltools is also still affected by:

https://github.com/timschmidt/stl2pov/issues/3

Given that my objects are oriented in an unexpected way.

It's trivial enough to work around by adding rotate <270, 0, 0> to my object declaration in povray, however ideally that shouldn't be required.

**Comment by pmjdebruijn** [comment]
I just noticed:
https://github.com/rsmith-nl/stltools/blob/master/stl2pov.py#L97

Thought my objects are still oddly oriented, while they are generated using OpenSCAD, slic3r for example orients them correctly.

**Comment by rsmith-nl** [comment]
Looks like I made a mistake. In STL, x,y,z are indices 0,1,2. In POV-ray I put them in 1,0,2. It should be 0,2,1.

**Comment by rsmith-nl** [comment]
The problem is, I have never been able to find a canonical reference for the coordinate system of STL files. Usually the coordinate system isn't mentioned *at all*.

**Comment by pmjdebruijn** [comment]
When lacking a proper reference, simply emulating behavior of other commonly used tools may be a good guide.

And I'd be happy to test any changes.

**Comment by rsmith-nl** [comment]
Just pushed b7e91273778c368b36dc5fd9abf6925b4e2e67d3, which changes the coordinates as described above.

**Comment by pmjdebruijn** [comment]
I just did a quick test, and it seems fine now:

So with rotate <270, 0, 0> it's wrong now (as one would expect)
And without rotate <270, 0, 0> it's right now (as it should be)

**Comment by rsmith-nl** [comment]
Ok.
