### ISSUE TITLE
potential parser.add_argument typo

### ISSUE THREAD

**Issue by pmjdebruijn** [rsmith-nl/stltools#12]
I'm not particularly skilled at Python, but this looks odd:

https://github.com/rsmith-nl/stltools/blob/master/stl2pov.py#L142

Compared to:

https://github.com/rsmith-nl/stltools/blob/master/stl2pov.py#L150

**Comment by rsmith-nl** [comment]
The `version` action *requires* a `version` keyword argument. See [the documentation](https://docs.python.org/3.5/library/argparse.html#action).

**Comment by pmjdebruijn** [comment]
I'm sorry, I shouldn't have made this issue an easter egg hunt...

Shouldn't    '-2,'    be    '-2',
