### ISSUE TITLE
cube-txt.stl test issue

### ISSUE THREAD

**Issue by pmjdebruijn** [rsmith-nl/stltools#13]
While trying to package stltools for Ubuntu 18.04, it seems that the following commit actually causes a regression:

https://github.com/rsmith-nl/stltools/commit/8e59493bb15a51b183d120ce131cf2c30f8d3078

Given that the intent of that commits was to fix something, I wonder if these some version dependant behavior here.

```
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:217: cd '/home/pmjdebruijn/Packages/stltools/stltools-5.0+12~g8e59493/.pybuild/cpython3_3.6/build'; python3.6 -m nose test
........F......
======================================================================
FAIL: test.test_stl.test_text
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pmjdebruijn/Packages/stltools/stltools-5.0+12~g8e59493/.pybuild/cpython3_3.6/build/test/test_stl.py", line 61, in test_text
    assert a == b
AssertionError
```

**Comment by rsmith-nl** [comment]
The test that failed was loading a (text) STL file, converting it back to text format and comparing it to the original. The original had multiple spaces, while the generated text only used one. So I changed the input to also use a single space; it was the easiest fix.


For me (at b7e91273778c368b36dc5fd9abf6925b4e2e67d3), all tests pass:

> cd test; py.test-3.7 -v test*.py
========================================== test session starts ==========================================
platform freebsd11 -- Python 3.7.4, pytest-4.5.0, py-1.8.0, pluggy-0.12.0 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/rsmith/src/progs/stltools
plugins: pylama-7.7.1
collected 15 items                                                                                      
> 
>test_matrix.py::test_vo_xform_scale PASSED                                                        [  6%]
test_matrix.py::test_vo_xform_trans PASSED                                                        [ 13%]
test_matrix.py::test_xform_rotx PASSED                                                            [ 20%]
test_matrix.py::test_xform_roty PASSED                                                            [ 26%]
test_matrix.py::test_xform_rotz PASSED                                                            [ 33%]
test_stl.py::test_read_bin PASSED                                                                 [ 40%]
test_stl.py::test_read_txt PASSED                                                                 [ 46%]
test_stl.py::test_normals PASSED                                                                  [ 53%]
test_stl.py::test_text PASSED                                                                     [ 60%]
test_utils.py::test_outnames PASSED                                                               [ 66%]
test_vecops.py::test_vo_length PASSED                                                             [ 73%]
test_vecops.py::test_vo_normalize PASSED                                                          [ 80%]
test_vecops.py::test_vo_normal PASSED                                                             [ 86%]
test_vecops.py::test_vo_indexate PASSED                                                           [ 93%]
test_vecops.py::test_vo_to PASSED                                                                 [100%]
> 
>======================================= 15 passed in 0.22 seconds =======================================

**Comment by pmjdebruijn** [comment]
With current git, it does not for me, with the commit i mentioned reverted it does apply:

```
stltools-5.0+13~gb7e9127/test$ py.test-3 -v test*.py
====================================================== test session starts ======================================================
platform linux -- Python 3.6.8, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3
cachedir: ../.cache
rootdir: /home/pmjdebruijn/Packages/stltools/f/stltools-5.0+13~gb7e9127, inifile:
collected 15 items                                                                                                              

test_matrix.py::test_vo_xform_scale PASSED                                                                                [  6%]
test_matrix.py::test_vo_xform_trans PASSED                                                                                [ 13%]
test_matrix.py::test_xform_rotx PASSED                                                                                    [ 20%]
test_matrix.py::test_xform_roty PASSED                                                                                    [ 26%]
test_matrix.py::test_xform_rotz PASSED                                                                                    [ 33%]
test_stl.py::test_read_bin PASSED                                                                                         [ 40%]
test_stl.py::test_read_txt PASSED                                                                                         [ 46%]
test_stl.py::test_normals PASSED                                                                                          [ 53%]
test_stl.py::test_text FAILED                                                                                             [ 60%]
test_utils.py::test_outnames PASSED                                                                                       [ 66%]
test_vecops.py::test_vo_length PASSED                                                                                     [ 73%]
test_vecops.py::test_vo_normalize PASSED                                                                                  [ 80%]
test_vecops.py::test_vo_normal PASSED                                                                                     [ 86%]
test_vecops.py::test_vo_indexate PASSED                                                                                   [ 93%]
test_vecops.py::test_vo_to PASSED                                                                                         [100%]

=========================================================== FAILURES ============================================================
___________________________________________________________ test_text ___________________________________________________________

    def test_text():
        vertices, name = stl.readstl('data/cube-txt.stl')
        facets, pnts = stl.toindexed(vertices)
        ni, nv = stl.normals(facets, pnts)
        res = stl.text('cube_txt', facets, pnts, ni, nv)
        res = [ln.strip() for ln in res.splitlines()]
        with open('data/cube-txt.stl') as inp:
            orig = [ln.strip() for ln in inp.readlines()]
        for a, b in zip(orig, res):
>           assert a == b
E           AssertionError: assert 'vertex 0. 0. 1.' == 'vertex  0.  0.  1.'
E             - vertex 0. 0. 1.
E             + vertex  0.  0.  1.
E             ?        +   +   +

test_stl.py:61: AssertionError
============================================== 1 failed, 14 passed in 0.08 seconds ==============================================

```

So there may be a behavioral difference between Python versions?

And then the question is, is there an elegant way around this?

**Comment by pmjdebruijn** [comment]
BTW, setup.py still has:

```
    extras_require={
        'test': ["nose>=1.3.0"],
    },

```

**Comment by rsmith-nl** [comment]
Updated setup.py in d8950afb5e0237c42f3fa5dddbc7333adb434b22.

**Comment by rsmith-nl** [comment]
The test failure is weird. It seems that the numpy that you use generates slightly different output from converting a vector to a string then the one I use. Since the *amount* of whitespace doesn't matter, I'll change the test to normalize whitespace.

**Comment by pmjdebruijn** [comment]
I just did a quick test, and it seems fine now.

**Comment by rsmith-nl** [comment]
Good. :-)

It's nice to have someone else look at this code and run it on another system. It improves its resilience!
