### ISSUE TITLE
test_stl.py relative paths

### ISSUE THREAD

**Issue by pmjdebruijn** [rsmith-nl/stltools#14]
While trying to package stltools for Ubuntu 18.04 I ran into the problem where test_stl.py contains paths that are relative to the test directory, as opposed to the project root directory, a 'chdir' shouldn't be required to succesfully run tests, and Debian's semi-automated python packaging tools assume test will run from the project root directory.

The fix is of course trivial:

```
-    vertices, name = stl.readstl('data/cube-bin.stl')
+    vertices, name = stl.readstl('test/data/cube-bin.stl')

```

And:

```
-    with open('data/cube-txt.stl') as inp:
+    with open('test/data/cube-txt.stl') as inp:
```

I can file a pull request if you want...

**Comment by rsmith-nl** [comment]
Already fixed it. :-)

**Comment by pmjdebruijn** [comment]
Confirmed fixed.
