### ISSUE TITLE
Several issues running on windows

### ISSUE THREAD

**Issue by Stoobiedoo** [rsmith-nl/stltools#3]
I'm running into two errors trying to run on windows.

Error; module 'mmap' has no attribute 'PROT_READ'
I believe this can be fixed with a change to the mmap call from
access=mmap.PROT_READ
to
access=mmap.ACCESS_READ

The second error may be related. After changing the mmap function to ACCESS_READ:
Error; a bytes-like object is required, not 'str'
I'm still looking for a solution to this issue.

**Comment by rsmith-nl** [comment]
A fix for the first part has been committed on the `develop` branch as f1a6e731. Can you post a complete backtrace for the second issue?
