### ISSUE TITLE
ImportError: No module named 'vecops'

### ISSUE THREAD

**Issue by kjcole** [rsmith-nl/stltools#5]
I'm on a Linux box with Python3 and numpy  1.12.1. I just installed a moment ago, and this is what I see:

```
$ stl2pov assembly_v4_rev3.stl 
Traceback (most recent call last):
  File "/usr/local/bin/stl2pov", line 33, in <module>
    from stltools import stl, utils
  File "/usr/local/lib/python3.5/dist-packages/stltools/stl.py", line 35, in <module>
    import vecops as vo
ImportError: No module named 'vecops'
```

**Comment by rsmith-nl** [comment]
I've just merged the develop branch into master to create version 4.0. This has been considerably reworked. Can you try if that fixes your problem?

**Comment by kjcole** [comment]
It fixes THAT problem but... See the NEW issue (to be filed in about 1 second). I don't know if they're related.
